import React from 'react'

function PrivacyPolicy(props:any) {
    return (
        <div id='policy'>
            <div className='policy'>
                <div className='policy-header'>Agreement That</div>
                <div className='policy-content'>
                    <div className='policy-content-inner'>
                        <div>
                            <h4>Our responsibilities:</h4>
                            <p>1. Protecting all data generated by and provided to us by our users from being stolen, compromised,or used in violation with this policy.</p>
                            <p>2. Never selling user-provided and user-generated data for financial gain or competitive advantage.</p>
                            <p>3. Providing transparency for our users into what data we collect and what we do with it including what access third parties have to user data and for what purpose.</p>
                            <p>4. Informing users if their data is compromised, either by failure to protect data or by order to surrender data to a legal authority, to the fullest extent we are lawfully able.</p>
                        </div>
                        <div>
                            <h4>Data we collect from you</h4>
                            <p>If you register an account with PCBONLINE.com, we’ll have access to your e-mail address and any additional contact information you choose to provide us. If you place an order, we retain a record of the contents of the order, delivery and billing address information, and any communication you might have with our sales people or engineering support teams about the order. If you browse PCBONLINE.com, with or without a login, we know for a limited time that a user at your IP address has visited pages on the site. We collect data on what products and content you browse in order to offer better value to you through personalized email, and to see which products/content are the most useful to you.</p>
                        </div>
                        <div>
                            <h4>Sending emails to you</h4>
                            <p>We send mail to you when the orders are placed, shipped, or ready for local pickup. We may also be in contact when an order requires payment before shipping, or if other issues prevent us from fulfilling an order.</p>
                            <p>We will notify you if we believe their privacy has been compromised, if it is within our power to do so. For example, if we discover a customer’s account user login information has been exposed elsewhere on the web, or if we are compelled to disclose information to law enforcement.</p>
                            <p>We may occasionally send you an email that you did not request or trigger with an action of any kind in order to promote a certain aspect of our site, products, or services.</p>
                        </div>
                        <div>
                            <h4>Interaction between PCBONLINE and you</h4>
                            <p>If you email us, chat with us, or call us on the telephone for support we can and most of the time will record the interaction.This is done so for training and audit purposes and the private conversations between customers and support staff are never sold to or shared with third parties.</p>
                        </div>
                        <div>
                            <h4>About website log</h4>
                            <p>In order to understand traffic to PCBONLINE.com and diagnose technical problems, we log individual web requests. These logs include time of request, individual IP address, referer, and user agent strings. We may retain these logs for up to 60 days, although individually-identifying information will be obscured after one week. In order to prevent fraud and detect malicious behavior, we log IP addresses for specific actions, such as creating a customer account and placing an order. This information is automatically deleted after no more than 60 days. Except in the case of malicious traffic, we will not share log data with any third party, unless compelled by legal process to do so.</p>
                        </div>
                        <div>
                            <h4>Cookies</h4>
                            <p>We use cookies to know when users are logged in to PCBONLINE services, and to track preferences such as display currencies and the rendering of product menus.</p>
                        </div>
                        <div>
                            <h4>Payment Providers</h4>
                            <p>Payments for buying PCBs at PCBONLINE.com are processed through Paypal. When using PayPal on PCBONLINE.com, a user should provide their PayPal email address. The user will then be directed to paypal.com to complete their payment, after which they will be redirected to PCBONLINE.com to complete the order. In case you do not have a Paypal account, credit card data including the cardholder name, credit card number, expiration date, CVV, and full billing address are sent to Paypal via an API for processing. Details regarding orders are not sent to Paypal. Each transaction is logged by retaining the transaction amount, the customer’s name, addresses and phone numbers. No any credit card data is stored at any point on PCBONLINE ’s servers.</p>
                        </div>
                    </div>
                </div>
                <div className='policy-footer'>
                    <button className='policy-btn' onClick={e => props.isAgreeOurPolicy(true)}>Argee</button>
                    <button onClick={e => props.isAgreeOurPolicy(false)}>Disargee</button> 
                </div>
            </div>
        </div>
    )
}

export default PrivacyPolicy